### ISSUE TITLE
Feature request: ID3 tags

### ISSUE THREAD

**Issue by wader** [jcalazan/youtube-audio-dl#11]
Would be really nice if some of the video information could be written as ID3 tags, author, title, publish date, description, thumbnail.

I tried to setup my own dev environment but failed :disappointed: is easiest using vagrant? should be `cd ansible; vagrant up` more or less? https://gist.github.com/wader/3f1fd3d3da203f43b6e9

**Comment by jcalazan** [comment]
Hey Mattias, sorry I haven't tried this on a Windows machine.  But easiest in my opinion is with Docker.

The error message seems to say it couldn't find Ansible:

```
The executable 'ansible-playbook' Vagrant is trying to run was not
found in the PATH variable.
```

**Comment by wader** [comment]
Got the site running with docker-compose after reverting 3cb4aa403cfe57fc0dc8b6df3d3ecf24e2e17c6e and using psycopg2 2.6.1(some source files was missing for gcc with 2.6 hmm).

But the site seems to hang after submitting a youtube URL. But i managed to fiddle around using a ipython console instead to try out the metadata stuff.
