### ISSUE TITLE
the postgresql does not works

### ISSUE THREAD

**Issue by rischanlab** [jcalazan/youtube-audio-dl#12]
I just think that probably any someone have same issue with me. 
I can download all of docker images but the postgresql can't start. I checked using `docker ps` and I could not find the postgresql. When I start  again all containers using command ` docker-compose up -d`

the postgresql just starting but when I check again with `ps` it still does not works.

Starting youtubeaudiodl_postgresql_1...
youtubeaudiodl_rabbitmq_1 is up-to-date
youtubeaudiodl_flower_1 is up-to-date
youtubeaudiodl_celery_1 is up-to-date
youtubeaudiodl_django_1 is up-to-date

[rischan@mbp ~/PycharmProjects/youtube-audio-dl (master)]$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                          NAMES
5f7ef4e75534        jcalazan/django     "bash -c 'sleep 3 && "   30 minutes ago      Up 11 minutes       0.0.0.0:80->80/tcp                             youtubeaudiodl_django_1
625b82b447ee        jcalazan/django     "bash -c 'sleep 3 && "   30 minutes ago      Up 11 minutes       80/tcp                                         youtubeaudiodl_celery_1
329973ce3925        jcalazan/django     "bash -c 'sleep 3 && "   30 minutes ago      Up 11 minutes       80/tcp, 0.0.0.0:5555->5555/tcp                 youtubeaudiodl_flower_1
74c309bc3669        jcalazan/rabbitmq   "/bin/sh -c /usr/sbin"   53 minutes ago      Up 11 minutes       4369/tcp, 0.0.0.0:15672->15672/tcp, 5672/tcp   youtubeaudiodl_rabbitmq_1

**Comment by jcalazan** [comment]
Hey @rischanlab , are you using Boot2Docker by any chance?  If you do, see note about it here: https://github.com/jcalazan/youtube-audio-dl#install-docker

**Comment by rischanlab** [comment]
Thanks @jcalazan for your comment. I found that in you repo homepage that docker postgis has a problem when we run in OSX.
