### ISSUE TITLE
Can't convert "Sorry, something went wrong. Please try again."

### ISSUE THREAD

**Issue by wader** [jcalazan/youtube-audio-dl#14]
Hi, there seems to be some problem with http://www.youtubeadl.com/ I get "Sorry, something went wrong. Please try again." when submitting URLs

**Comment by jcalazan** [comment]
Hi Mattias, thanks for reporting this and sorry for the delay! The service should be back up and running now.

**Comment by wader** [comment]
No problem, thanks for fixing!

**Comment by wader** [comment]
Still a bit flaky, trying to convert https://www.youtube.com/watch?v=RINk9MhQ85Q to long?

**Comment by wader** [comment]
Hi, seems to be broken again 😞

**Comment by jcalazan** [comment]
Hey Mattias,

I reverted back my old code and it should be working fine now and should convert faster.

**Comment by wader** [comment]
👍
