### ISSUE TITLE
Building on AWS

### ISSUE THREAD

**Issue by aspats** [jcalazan/youtube-audio-dl#3]
Hi jcalazan,

I am happy that you updated your code :). I am quite new with django. I am using your older "youtube-audio-dl" code just for learning and building it on Amazon. So now your older code is working quite good in amazon (I am using not for to converting youtube videos but for images recognozicion from link).  Just was one time when celeryd crashed and supervisor didn't work well to restart. 
I am intresting to try a new version of your code for amazon, but I don't understand well what I should do to make for production in amazon. Because now I understand that description are for local. Maybe will not be so diffucult to write some part of description how to build it on amazon? Just where to put in code DNS adress and all small stuff which need to work in amazon?
Thank you jcalazan :)

**Comment by jcalazan** [comment]
Hey aspats,

I use [Ansible](http://www.ansible.com/) to automate my deploying to Digital Ocean.  Here's more info on how I do it: https://github.com/jcalazan/ansible-django-stack (I will be updating this project pretty soon as well as I've just recently refactored it).

If you're new to Django, I recommend to check out this very detailed blog post for deploying Django apps to a Linux server: http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/

That's pretty much how I have my prod servers configured.

**Comment by aspats** [comment]
I was trying to build on AWS "youtube-audio-dl", but I got a problem when I run 
ansible-playbook -l 'tag_Name_Aminator' -v /home/geras/Documents/youtube-audio-dl/ansible/vagrant.yml:
In the end I got this:

TASK: [db | Ensure the PostgreSQL service is running] ************************* 
changed: [5x.2x.7x.2xx] => {"changed": true, "enabled": true, "item": "", "name": "postgresql", "state": "started"}

TASK: [db | Ensure database is created] *************************************** 
failed: [5x.2x.7x.2xx] => {"failed": true, "item": ""}
msg: unable to connect to database: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by aspats** [comment]
Hey jcalazan,

I build your project in AWS. Now I will try to describe bugs which was deploying and how to solve it. I hope you will update your code :):

1) When you finish install postgres databse you miss to start cluster:
        pg_createcluster 9.3 main --start
        /etc/init.d/postgresql start
2) Can't to install ffmpeg. The solution:
        sudo add-apt-repository ppa:mc3man/trusty-media
        sudo apt-get update
        sudo apt-get install ffmpeg gstreamer0.10-ffmpeg
3) I don't have any emails services to use for this project so I comment all code parts where are "email_host_password" or some information with email.
4) Ansible doesn't copy youtube-audio-dl project to server so I make by hand:
       cd /webapps/youtubeadl/
       git clone https://github.com/jcalazan/youtube-audio-dl 
5) If you installing two ore more servers (1 dbserver and 1 or more webserver) then there are some problems:
        a) You should make configuration that dbserver let connect postgres from another webservers. 
        b) Change in all webservers django setting files. You need to change databse adress to dbserver adress (from 127.0.0.1 to dbserver adress).
6) If you are using more then two webservers you should make one more servers for load balancing. Just make one server for nginx to balance all webservers.

So with those steps I could use you project in AWS and to have mores then two serves. Now I am testing with 5 servers (1 dbserve, 4 webservers and 1 load balancer).
If you need I could help some how to develop your project. I am learning fast.

**Comment by jcalazan** [comment]
Thanks for info aspats.  I'm closing the ticket because it's a bit off-topic here and I'd like to keep this repo specific to app development as there are many different ways to deploy the app.
