### ISSUE TITLE
Many servers

### ISSUE THREAD

**Issue by aspats** [jcalazan/youtube-audio-dl#5]
Hi jcalazan,

For example we have million requests in "youtube-audio-dl" project on web and I want to build many "youtube-adio-dl" servers on AWS t1.micro and I would like to have one domain. I don't know what I should use to mannage requests and distribute it for t1.micro servers. Requirement is that one t1.micro server could accept just one request.

**Comment by jcalazan** [comment]
Hi aspats, 

Deployment and server configuration could really vary.  I'd like to keep this repo specific to the app.  If you use Ansible, I have a separate project here: https://github.com/jcalazan/ansible-django-stack

For multiple server deployments, consider using a load balancer (Amazon also has an ELB service).  Ansible has modules for these types of configuration: http://docs.ansible.com/guide_aws.html
