### ISSUE TITLE
Migrate fails

### ISSUE THREAD

**Issue by epicserve** [jcalazan/youtube-audio-dl#7]
When I run ``docker-compose run django python manage.py migrate`` I get the following:

```
Starting youtubeaudiodl_postgresql_1...
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

2015-05-01 22:58:07,820  [py.warnings:7]  WARNING - /usr/local/lib/python2.7/dist-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 180, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 172, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: could not connect to server: No route to host
	Is the server running on host "postgresql" (172.17.0.51) and accepting
	TCP/IP connections on port 5432?
```

I also noticed in the logs the following:

```
postgresql_1 | 2015-05-01 22:55:05 UTC FATAL:  "/var/lib/postgresql/9.1/main" is not a valid data directory
postgresql_1 | 2015-05-01 22:55:05 UTC DETAIL:  File "/var/lib/postgresql/9.1/main/PG_VERSION" is missing.
postgresql_1 | 2015-05-01 22:55:39 UTC FATAL:  "/var/lib/postgresql/9.1/main" is not a valid data directory
postgresql_1 | 2015-05-01 22:55:39 UTC DETAIL:  File "/var/lib/postgresql/9.1/main/PG_VERSION" is missing.
```

**Comment by jcalazan** [comment]
Hey Brent,

Can you try deleting the `~/dockerfiles` directory and try again?  These files should be recreated when the containers start.

**Comment by epicserve** [comment]
I tried that, same issue. I'm using boot2docker on a MacBook Pro, fwiw.

**Comment by jcalazan** [comment]
Can you check if `~/dockerfiles/youtube-audio-dl/postgresql/9.1/main` exists?  If it's there my guess is something with the boot2docker VM sharing, could be a permission issue.

**Comment by jcalazan** [comment]
I think boot2docker mounts the `/Users` directory by default, another thing we can try is change these lines in the `docker-compose.yml`:

From: `~/dockerfiles/youtube-audio-dl` 
To: `/Users/[your-user]/dockerfiles/youtube-audio-dl`

**Comment by epicserve** [comment]
It exists.

```
$ ls -la ~/dockerfiles/youtube-audio-dl/postgresql/9.1/main
total 0
drwxr-xr-x  2 brento  staff   68 May  4 08:14 .
drwxr-xr-x  3 brento  staff  102 May  4 08:14 ..
```

**Comment by jcalazan** [comment]
if you do `boot2docker ssh`, is the main folder there? `/var/lib/postgresql/9.1/main`

**Comment by epicserve** [comment]
No.

```
$ boot2docker ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.6.0, build master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
Docker version 1.6.0, build 4749651
docker@boot2docker:~$ /var/lib/
-sh: /var/lib/: Permission denied
docker@boot2docker:~$ ll
total 4
----------    1 docker   staff           29 Jan  1  1970 boot2docker, please format-me
docker@boot2docker:~$ ls /var/lib/
boot2docker  docker       nfs/
docker@boot2docker:~$ ls -la /var/lib/
total 0
drwxrwxr-x    3 root     staff          100 May  7 00:08 ./
drwxrwxr-x    8 root     staff          180 May  7 00:08 ../
lrwxrwxrwx    1 root     root            29 May  7 00:08 boot2docker -> /mnt/sda1/var/lib/boot2docker/
lrwxrwxrwx    1 root     root            24 May  7 00:08 docker -> /mnt/sda1/var/lib/docker/
drwxr-xr-x    4 root     root           160 May  7 00:08 nfs/
```

**Comment by epicserve** [comment]
Also the same message in the logs:

```
postgresql_1 | 2015-05-07 18:45:09 UTC FATAL:  "/var/lib/postgresql/9.1/main" is not a valid data directory
postgresql_1 | 2015-05-07 18:45:09 UTC DETAIL:  File "/var/lib/postgresql/9.1/main/PG_VERSION" is missing.
```

**Comment by jcalazan** [comment]
Sorry, `/var/lib/...` would actually mounted in the container.  In `boot2dockervm`, let's check for `/Users/[your-user]/dockerfiles/youtube-audio-dl/postgresql/9.1/main`

**Comment by epicserve** [comment]
Isn't ``boot2docker ssh`` just ssh'ing into the host VM. Why would it mount to ``/Users``? Wouldn't you need to ssh into the postgres container to check for the correct mount?

**Comment by epicserve** [comment]
Also if I do ``docker ps`` it shows the following:

```
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                                          NAMES
15a70f9487ee        jcalazan/django:latest     "bash -c 'sleep 3 &&   18 minutes ago      Up 18 minutes       0.0.0.0:80->80/tcp                             youtubeaudiodl_django_1
31de36a0220b        jcalazan/django:latest     "bash -c 'sleep 3 &&   18 minutes ago      Up 18 minutes       80/tcp                                         youtubeaudiodl_celery_1
4c2abd391d9f        jcalazan/django:latest     "bash -c 'sleep 3 &&   18 minutes ago      Up 18 minutes       80/tcp, 0.0.0.0:5555->5555/tcp                 youtubeaudiodl_flower_1
d67d2a4d43da        jcalazan/rabbitmq:latest   "/bin/sh -c /usr/sbi   18 minutes ago      Up 18 minutes       4369/tcp, 5672/tcp, 0.0.0.0:15672->15672/tcp   youtubeaudiodl_rabbitmq_1
```

Shouldn't youtubeaudiodl_postgresql_1 be listed?

**Comment by jcalazan** [comment]
According to their documentation, they mount it automatically: https://github.com/boot2docker/boot2docker#virtualbox-guest-additions

Yup, the ssh just goes to the VM.  The SSH service is actually not running in the containers, you can get access to the shell in the container with `docker-compose run postgresql /bin/bash`

But my guess is the issue is something with the directory sharing or permission related.

For the postgresql and python files, it may be better to just keep all these files in the VM, outside of the Mac -> VM sharing (normally it's just the code that we need shared here).  Instead of mounting `~/dockerfiles`, we can try just `/dockerfiles`, which I think will just create the folder and files inside the VM, so nothing is stored on the host Mac machine and could resolve the permission issues (if it turns out to be the case).

**Comment by jcalazan** [comment]
Oh for the docker ps stuff, the postgresql container probably stopped because of the error with the data directory.

**Comment by epicserve** [comment]
So what are the next steps? Do you have a Mac you can try this on and then push up a fix? I'm just learning docker/docker-compose so I'm probably not a ton of help. :)

**Comment by epicserve** [comment]
Seems like what you were saying is reasonable ... wouldn't the only done side be that if you ran ``docker-compose kill`` you would lose your data in the database?

**Comment by jcalazan** [comment]
I don't unfortunately, I'm on Ubuntu and Docker works a lot nicer here (no extra VM needed).

The reason we're actually mounting the volume is to not lose the data when we stop/delete the containers.

One thing you could try is in `docker-compose.yml`, change the first entry to this:

```
postgresql:
  image: jcalazan/postgresql
  environment:
    - POSTGRESQL_DB=youtubeadl
    - POSTGRESQL_USER=youtubeadl
    - POSTGRESQL_PASSWORD=password
  volumes:
    - /dockerfiles/youtube-audio-dl/postgresql:/var/lib/postgresql
  ports:
    - "5432:5432"
```

Basically just remove the `~`. 

Then run: `docker-compose postgresql up` and see if any errors.

I'm expecting the the postgresql files will just be store in `/dockerfiles/...` inside the VM (so no files should be created on your machine).

**Comment by epicserve** [comment]
Removing the ~ worked.

BTW, you're blog post doesn't tell people how to pull up the site after the step 6. I figured it out though.

I got the IP with `boot2docker ip` then discovered that the runserver is running on port 80, so I pulled up that ip in my browser and got the "YouTube Audio Downloader" page.

**Comment by jcalazan** [comment]
Ah yeah, good point, I wasn't thinking about non-Linux users.  I'll update it in a bit and the README as well. Thanks!

Btw, you might want to remove the '~' as well for the rest of the `docker-compose.yml` file just to keep all the extra files inside the VM in case some other weird permission issues come up (you'll need to run the `pip install` again, then you can remove that `~/dockerfiles` directory on your Mac).  Might be cleaner that way.

**Comment by epicserve** [comment]
Regarding removing '~', I got it working and that was my goal. I'm new to docker and docker-compose, just trying to learn the tool to see if I should consider it for future projects. In other words, I was just playing around, so I'll probably move on now.

I'm sort of disappointed that it didn't just work, it seems like the point of docker/vagrant, etc. is that it should just work no matter what platform you're on. It's too bad that because you were using Ubuntu for your host, you didn't know it wouldn't work on OSX/boot2docker until someone tried it.
