### ISSUE TITLE
Strip slashes in filename

### ISSUE THREAD

**Issue by jcalazan** [jcalazan/youtube-audio-dl#8]
We need to strip slashes as it will be treated as part of a the filepath.

**Comment by statwonk** [comment]
@jcalazan first, I want to thank you for your tutorial and this app. I just finished erecting the app and feel like I learned a TON! Thank you! I did however get bit pretty hard by the `User` / `~` issue (as I'm on OSX as well). I just wanted you to know that I think this is a bug worth fixing. :+1:

**Comment by jcalazan** [comment]
You're welcome @statwonk , glad you found it useful :)

There's currently an opened ticket in `boot2docker` related to the `User` share issue: https://github.com/boot2docker/boot2docker/issues/581
